name: olivaw-test
on: push

env:
  MAIN: 'main'
jobs:
  olivaw-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - run: |
        IFS='/' read -ra PATHS <<< "${{ github.ref }}"
        echo "BRANCH=$(echo ${PATHS[2]})" >> $GITHUB_ENV
    - uses: Wimmics/olivaw/test-actions@v0.0.6
      with:
        gist-secret: ${{ secrets.GIST_SECRET }}
        commit-report: ${{ env.BRANCH == env.MAIN }}
